service: aws-turn-off-my-account

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'prod'}
  timeout: 300
  memorySize: 256
  versionFunctions: false

  tags:
    GLOBALTAG1: foo
    GLOBALTAG2: bar

  iamRoleStatements:

  - Effect: Allow
    Action:
      - ec2:*
      - rds:*
      - sqs:*
      - cloudwatch:*
      - logs:* 
    Resource: "*"

  environment:
    ${file(./configs/${self:provider.stage}.yml)}

package:
  exclude:
    - ./**
    - .git/**
    - .vscode/**
    - .test/**
  include:
    - ./bin/**

custom:
  region: ${self:provider.region}
  stage:  ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  dynamo-books-name: ${self:custom.prefix}-books-catalog
  sqs-books-name: ${self:custom.prefix}-processing-queue

functions:
  worker:
    handler: bin/worker
